function sys=Ethernetref
sys = [];
sys.child = [];
sys.NumDataTypes = 4; 
sys.DataTypes = [];
temp.EnumNames='';
temp.EnumValues = [];
temp.Name = '';
sys.DataTypes = repmat(temp,1,4);
sys.DataTypes(1).Name = 'int32_T';
sys.DataTypes(2).Name = 'int16_T';
sys.DataTypes(3).Name = 'uint8_T';
sys.DataTypes(4).Name = 'real_T';
